apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsubnets.aws.platformref.upbound.io
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: aws.platformref.upbound.io/v1alpha1
    kind: XSubnet
  resources:
    - name: vpc
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            region: eu-central-1
            cidrBlock: 10.0.0.0/16
      patches:
        - fromFieldPath: spec.vpcName
          toFieldPath: spec.forProvider.tags.Name
    - name: subnet
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        spec:
          forProvider:
            region: eu-central-1
            cidrBlock: 10.0.1.0/24
            vpcIdSelector:
              matchControllerRef: true
